version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
install:
  - ps: appveyor DownloadFile http://znix.xyz/random/ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: 7z x -olibovr ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: ./configure.cmd
build:
  project: OpenOVR.sln
  verbosity: minimal
artifacts:
  - path: $(platform)/$(configuration)/openvr_api.dll
    name: OpenOVR-$(configuration)-$(platform)
